before:
  hooks:
    - go mod download

builds:
  - main: .
    id: botastic
    binary: botastic
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}}
dockers:
  - id: botastic
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - "ghcr.io/zuodaotech/{{ .ProjectName }}/botastic:latest"
      - "ghcr.io/zuodaotech/{{ .ProjectName }}/botastic:{{ .Major }}"
      - "ghcr.io/zuodaotech/{{ .ProjectName }}/botastic:{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/zuodaotech/{{ .ProjectName }}/botastic:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
blobs:
  - provider: s3
    region: us-east-2
    bucket: goreleaser-builds
    folder: "botastic"
