before:
  hooks:
    - go mod download

builds:
  - main: .
    id: botastic
    binary: botastic
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}}
dockers:
  - id: botastic
    goos: linux
    goarch: amd64
    dockerfile: .goreleaser.Dockerfile
    image_templates:
      - "ghcr.io/pandodao/botastic:latest"
      - "ghcr.io/pandodao/botastic:{{ .Major }}"
      - "ghcr.io/pandodao/botastic:{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/pandodao/botastic:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
