db:
  driver: "postgres"
  dsn: "user=postgres dbname=botastic host=localhost password=postgres sslmode=disable"

openai:
  keys: ["YOUR_KEY"]
  timeout: 10s

sys:
  secret_key: ""

milvus:
  address: "localhost:19530"

mixpay:
  payee_id: "USER_UUID"
  quote_asset_id: "31d2ea9c-95eb-3355-b65b-ba096853bc18"
  settlement_asset_id: "31d2ea9c-95eb-3355-b65b-ba096853bc18"
  callback_url: "$API_HOST/api/callback/mixpay"

auth:
  jwt_secret: "abc123"
  mixin_client_secret: "...."
